### ISSUE TITLE
Numba backend

### ISSUE THREAD

**Issue by datnamer** [joschu/cgt#2]
May be worth keeping in mind support for numba: https://github.com/numba/numba 

Supports multithreading in pure python syntax, is on the order of fortran fast and easily conda installable.

**Comment by twiecki** [comment]
I think this is definitely worth considering as writing your own Python-to-C++ compiler engine is an arduous task. numba also has GPU support.

**Comment by joschu** [comment]
Numba is a really excellent project, but I don't think it's the right fit here, since CGT's native backend uses some non-trivial C++ functionality, so it's more straightforward to implement the numerical operations in C++. That said, it's worth keeping numba in mind. The numba project also has some functionality for convenient LLVM code generation, which might be useful at some point.
